// Defines custom options used internally at Modal.
// Custom options must be in the range 50000-99999.
// Reference: https://protobuf.dev/programming-guides/proto2/#customoptions

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.6
// source: modal_proto/options.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_modal_proto_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50000,
		Name:          "modal.options.audit_target_attr",
		Tag:           "varint,50000,opt,name=audit_target_attr",
		Filename:      "modal_proto/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50000,
		Name:          "modal.options.audit_event_name",
		Tag:           "bytes,50000,opt,name=audit_event_name",
		Filename:      "modal_proto/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "modal.options.audit_event_description",
		Tag:           "bytes,50001,opt,name=audit_event_description",
		Filename:      "modal_proto/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool audit_target_attr = 50000;
	E_AuditTargetAttr = &file_modal_proto_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional string audit_event_name = 50000;
	E_AuditEventName = &file_modal_proto_options_proto_extTypes[1]
	// optional string audit_event_description = 50001;
	E_AuditEventDescription = &file_modal_proto_options_proto_extTypes[2]
)

var File_modal_proto_options_proto protoreflect.FileDescriptor

const file_modal_proto_options_proto_rawDesc = "" +
	"\n" +
	"\x19modal_proto/options.proto\x12\rmodal.options\x1a google/protobuf/descriptor.proto:N\n" +
	"\x11audit_target_attr\x12\x1d.google.protobuf.FieldOptions\x18І\x03 \x01(\bR\x0fauditTargetAttr\x88\x01\x01:M\n" +
	"\x10audit_event_name\x12\x1e.google.protobuf.MethodOptions\x18І\x03 \x01(\tR\x0eauditEventName\x88\x01\x01:[\n" +
	"\x17audit_event_description\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\tR\x15auditEventDescription\x88\x01\x01B&Z$github.com/modal-labs/modal/go/protob\x06proto3"

var file_modal_proto_options_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil),  // 0: google.protobuf.FieldOptions
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_modal_proto_options_proto_depIdxs = []int32{
	0, // 0: modal.options.audit_target_attr:extendee -> google.protobuf.FieldOptions
	1, // 1: modal.options.audit_event_name:extendee -> google.protobuf.MethodOptions
	1, // 2: modal.options.audit_event_description:extendee -> google.protobuf.MethodOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_modal_proto_options_proto_init() }
func file_modal_proto_options_proto_init() {
	if File_modal_proto_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modal_proto_options_proto_rawDesc), len(file_modal_proto_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_modal_proto_options_proto_goTypes,
		DependencyIndexes: file_modal_proto_options_proto_depIdxs,
		ExtensionInfos:    file_modal_proto_options_proto_extTypes,
	}.Build()
	File_modal_proto_options_proto = out.File
	file_modal_proto_options_proto_goTypes = nil
	file_modal_proto_options_proto_depIdxs = nil
}
